### ISSUE TITLE
Do you still like using rpms to deploy your rails apps?

### ISSUE THREAD

**Issue by kbrock** [tilo/deploy_rails_as_rpm#2]
Hello @tilo 

Quite a few years have passed since you put this gem together.
Curious if you transitioned to containers or if you use rpms to install in containers / others.

We are currently using rpms for our rails packages, but I was curious about filesystem user privileges for your rpms.

Did you run your apps with one user and install your rpms as another user?
Asked another way, the `webapp` user can modify files in `tmp/`, but can they modify 'app/models/user.rb'?

Well, I've seen you around the community and wanted to say thank you for your contributions.

**Comment by tilo** [comment]
@kbrock this was a very long time ago.. before containers.

I think I installed as root, and then chown'ed it to a deploy user, which was in the same group as the webapp user that ran the code.
RPMs have pre- and post-installations scripts, so you can chown the files after install.

You'd want the user that runs the server to be different from the owner of the code, so the code can not be modified at runtime.

**Comment by kbrock** [comment]
thank you
